# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-18 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_profile_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rpg_class',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
