# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-18 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_profile_rpg_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
    ]
