# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-18 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20171218_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='games_liked',
            field=models.ManyToManyField(related_name='self', to='app.Game'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='games_owned',
            field=models.ManyToManyField(to='app.Game'),
        ),
    ]
