# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-18 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20171218_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='games_liked',
            field=models.ManyToManyField(related_name='_profile_games_liked_+', to='app.Profile'),
        ),
    ]
