# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-18 21:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20171218_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='games_liked',
        ),
    ]
