# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-18 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_profile_games_owned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='games_owned',
            field=models.ManyToManyField(related_name='_profile_games_owned_+', to='app.Profile'),
        ),
    ]
