# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-19 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20171218_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
