# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20171219_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, height_field=512, upload_to='avatars', width_field=512),
        ),
    ]
